[tool.poetry]
name = "root"
version = "0.0.0"

[tool.poetry.dependencies]
python = "==3.9"
requests = "*"
beautifulsoup4 = "*"
lxml = "*"
requests-html = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
